# language: php # linux only
language: bash # cross-platform

os:
    - linux
    - osx
    - windows

dist: xenial

env:
  global:
    - COLLECT_COVERAGE=false
    - PHPENV_ROOT=/usr/local/bin/phpenv
  matrix:
    - _PHP=hhvm # developed by facebook
    - _PHP=5.6 _PKG=php
    - _PHP=7.0 _PKG=php
    - _PHP=7.1 _PKG=php
    - _PHP=7.2 _PKG=php
    - _PHP=7.3 _PKG=php

matrix:
  fast_finish: true
  exclude:
    - os: osx
      env: _PHP=5.6 _PKG=php
    - os: osx
      env: _PHP=7.0 _PKG=php
    - os: windows
    - os: linux
  include:
    - os: linux
      language: php
      php: '7.0'
      env: _PHP=7.0 _PKG=php PHPENV_ROOT=~/.phpenv
    - os: linux
      language: php
      php: 'hhvm'
      env: _PHP=hhvm PHPENV_ROOT=~/.phpenv
    - os: osx
    - os: windows
      env: _PHP=7.3 _PKG=php
    - os: windows
      env: _PHP=hhvm
  allow_failures:
    - env: _PHP=hhvm
    - env: _PHP=7.3 _PKG=php

addons:
  apt:
    packages:
      - php7.0
      - php7.0-xml
      - hhvm
    update: true

before_install:
  - source build/phpenv_install.sh
  - source build/prepare_${TRAVIS_OS_NAME}_env.sh #; source exports
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${_PHP}" == 7* ]]; then COLLECT_COVERAGE=true ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${COLLECT_COVERAGE}" != "true" ]]; then phpenv config-rm xdebug.ini || true ; fi
  - if [ ! -z "${ADDITIONAL_PHP_INI}" ]; then build/custom_php_ini.sh; fi

install:
  - if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then build/handle_${TRAVIS_OS_NAME}_pkg.sh "openssl.light" "" ""; fi
  - if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then build/handle_${TRAVIS_OS_NAME}_pkg.sh "${_PKG}" "${_PHP}" "--with-openssl"; fi
  - if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then build/handle_${TRAVIS_OS_NAME}_pkg.sh "composer"; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then curl -s http://getcomposer.org/installer | php; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then php composer.phar install --dev --no-interaction; fi

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${_PHP}" == "hhvm" ]]; then curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar; fi
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml --stop-on-failure

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi
