language: generic

matrix:
  fast_finish: true

  include:
    - os: linux
      php: '5.6'

    - os: linux
      php: '7.0'

    - os: linux
      php: 'nightly'

    - os: linux
      php: 'hhvm'

    - os: osx
      env: _PHP=php@5.6

    - os: osx
      env: _PHP=php@7.0

    - os: osx
      env: _PHP=php@7.1

    - os: osx
      env: _PHP=php@7.2

  allow_failures:
    - php: hhvm
    - env: _PHP=php@7.1
    - env: _PHP=php@7.2

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_PHP_VERSION}" == 7* ]]; then COLLECT_COVERAGE=true ; fi
  - if [[ "${COLLECT_COVERAGE}" != "true" ]]; then phpenv config-rm xdebug.ini || true ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash build/prepare_osx_env.sh ; fi

install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash build/handle_brew_pkg.sh "${_PHP}" ; fi
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

before_script:
  - if [ ! -z "${ADDITIONAL_PHP_INI}" ]; then /usr/bin/env bash build/custom_php_ini.sh; fi
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit --coverage-php build/cov/coverage-${component_name}.cov . | grep error

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then travis_retry php vendor/bin/coveralls -v ; fi
