# language: php # linux only
language: generic

os:
    - linux
    - osx

dist: trusty

env:
  - _PHP=hhvm
  - _PHP=5.6 _PKG=php
  - _PHP=7.1 _PKG=php
  - _PHP=7.2 _PKG=php
matrix:
  fast_finish: true

  allow_failures:
    - env: _PHP=hhvm
    - os: linux
      env: _PHP=7.2 _PKG=php

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then phpenv global ${_PHP} && composer self-update; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then phpenv --version && composer --version; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${_PHP}" == 7* ]]; then COLLECT_COVERAGE=true ; fi
  - if [[ "${COLLECT_COVERAGE}" != "true" ]]; then phpenv config-rm xdebug.ini || true ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash build/prepare_osx_env.sh ; fi

install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then /usr/bin/env bash build/handle_brew_pkg.sh "${_PKG}" "${_PHP}" ; fi
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${_PHP}" == "hhvm" ]]; then curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar; fi
  - if [ ! -z "${ADDITIONAL_PHP_INI}" ]; then /usr/bin/env bash build/custom_php_ini.sh; fi
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml --stop-on-failure

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi
