# language: php # linux only
language: bash # cross-platform

os:
    - linux
    - osx
    - windows

dist: bionic
addons:
  apt:
    sources:
    - sourceline: ppa:ondrej/php
  homebrew:
    packages:
    - bash
env:
  global:
    - COLLECT_COVERAGE=false
    - PHPENV_ROOT=/usr/local/bin/phpenv
    - _SSL=openssl
  matrix:
    - _PHP=7.2 _PKG=php PHPENV_ROOT=~/.phpenv
    - _PHP=7.3 _PKG=php PHPENV_ROOT=~/.phpenv

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx
    - os: windows
  allow_failures:
    - os: windows

before_install:
  - source build/phpenv_install.sh
  - source build/prepare_${TRAVIS_OS_NAME}_env.sh #; source exports
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${_PHP}" == 7* ]]; then COLLECT_COVERAGE=true ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${COLLECT_COVERAGE}" != "true" ]]; then phpenv config-rm xdebug.ini || true ; fi
  - if [ ! -z "${ADDITIONAL_PHP_INI}" ]; then build/custom_php_ini.sh; fi
  - build/handle_${TRAVIS_OS_NAME}_pkg.sh "${_SSL}" "latest";
  - if [[ "${TRAVIS_OS_NAME}" != "windows" ]]; then [ $(which c_rehash) > /dev/null ] && sudo c_rehash; fi
  - build/handle_${TRAVIS_OS_NAME}_pkg.sh "curl" "latest" "--with-openssl" | tail
  - build/handle_${TRAVIS_OS_NAME}_pkg.sh "${_PKG}" "${_PHP}" "--with-homebrew-curl"
  - build/handle_${TRAVIS_OS_NAME}_pkg.sh "${_PKG}" "${_PHP}-xml" | tail
  - php -i | grep "SSL Version"
  - build/handle_${TRAVIS_OS_NAME}_pkg.sh "composer" "latest" | tail

install:
  - composer require --no-interaction

before_script:
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi
