# language: php # linux only
language: bash # cross-platform

os:
    - linux
    - osx
    - windows

dist: trusty

env:
  global:
    - COLLECT_COVERAGE=false
    - PHPENV_ROOT=/usr/local/bin/phpenv
    - _SSL=openssl
  matrix:
    - _PHP=latest _PKG=hhvm PHPENV_ROOT=~/.phpenv # developed by facebook, trusty only
    - _PHP=7.0 _PKG=php PHPENV_ROOT=~/.phpenv
    - _PHP=7.4 _PKG=php PHPENV_ROOT=~/.phpenv

matrix:
  fast_finish: true
  include:
    - os: linux
    - os: osx
    - os: windows
  allow_failures:
    - env: _PHP=latest _PKG=hhvm PHPENV_ROOT=~/.phpenv
    - env: _PHP=7.4 _PKG=php PHPENV_ROOT=~/.phpenv
    - os: windows

before_install:
  - source build/phpenv_install.sh
  - source build/prepare_${TRAVIS_OS_NAME}_env.sh #; source exports
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${_PHP}" == 7* ]]; then COLLECT_COVERAGE=true ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${COLLECT_COVERAGE}" != "true" ]]; then phpenv config-rm xdebug.ini || true ; fi
  - if [ ! -z "${ADDITIONAL_PHP_INI}" ]; then build/custom_php_ini.sh; fi

install:
  - if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then export _SSL=openssl.light; fi
  - build/handle_${TRAVIS_OS_NAME}_pkg.sh "${_SSL}" "latest"; [ $(which c_rehash) > /dev/null ] && c_rehash
  - build/handle_${TRAVIS_OS_NAME}_pkg.sh "${_PKG}" "${_PHP}" "--with-openssl"
  - build/handle_${TRAVIS_OS_NAME}_pkg.sh "${_PKG}" "${_PHP}-xml"
  - if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then build/handle_${TRAVIS_OS_NAME}_pkg.sh "composer" "latest"; bash -c 'composer install --dev --no-interaction'; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then curl -s http://getcomposer.org/installer | php && php composer.phar install --dev --no-interaction; fi

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" && "${_PHP}" == "hhvm" ]]; then curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar; fi
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml --stop-on-failure

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then travis_retry php vendor/bin/php-coveralls -v ; fi
